[package]
name = "efivar-store-uefi"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "UEFI variable services with a persistent block-backed store"

[features]
lab = []

[dependencies]
efivar-store = { path = "../efivar-store" }
r-efi = { version = "=6.0.0", default-features = false }

[lints]
workspace = true
